// Description
//   Gives UQCSbot the shittalking ability of your average cod player
//
// Commands:
//   !`shittalk` - Responds with interesting trivia about your mum
//
//
module.exports = function (robot) {
  var responses = [
    "Team Fortress 2 is also Free-To-Uninstall",
    "If the body is 70% water how are you 100% salt???",
    "You're the reason the gene pool needs a lifeguard.",
    "I have neither the time, nor the crayons, to explain this to you.",
    "I'm jealous of people that don't know you.",
    "Your birth certificate is an apology letter from the condom factory.",
    "I would insult you but nature did a better job.",
    "Don't worry guys, I'm a garbage collector. I'm used to carrying trash.",
    "Perhaps your strategy should include trying.",
    "I'm not questioning your intelligence, merely denying its existence",
    "You must really like that respawn timer",
    "I'd tell you to commit suicide, but then you'd have a kill.",
    "Some people get paid to suck, you do it for free.",
    "You're the human equivalent of a participation award.",
    "You have worse map awareness than Christopher fucking Columbus.",
    "I'd tell you to go outside, but you'd just ruin that for everyone else too",
    "At least your ping score is higher than mine.",
    "if i wanted to kill myself id jump from your ego to your IQ",
    "With aim like that, I pity whoever has to clean the floor around your toilet",
    "You have the situational awareness of a potato",
    "You have the situational awareness of a potato",
    "I hope one day you regain the use of your hands.",
    "Are you aiming for a pacifist walkthrough?",
    "Your kills are like all Valve franchises, stuck at 2",
    "The keys you're looking for are Alt-F4",
    "I'd love to see things from your perspective, but I don't think I could shove my head that far up my ass.",
    "You know all those times your parents said video games would get you nowhere? They were right.",
    "Does your ass get jealous of all the shit that comes out of your mouth?",
    "**PROTIP** Your crosshair generally assists you in aiming.",
    "Your birth certificate is an apology from the condom factory.",
    "Everyone who loves you is wrong.",
    "have you ever had a conversation where the other person wasn't just shaking their head in disappointment?",
    "Might I suggest you beat the tutorial first",
    "You are what you eat, and you're a dick.",
    "Try playing the game normally, instead of just repeatedly slamming your forehead into the keyboard.",
    "Even Noah can't carry these animals",
    "i don't know what gets less hits... your aim or your online dating profile",
    "Shut up, you'll never be the man your mother is.",
    "Are your parents siblings?",
    "You're lagging so hard you're still in 2015",
    "Maybe you should try a single-player game.",
    "Maybe you should try something more on your level, like rock-paper-scissors.",
    "Turning on your monitor would help.",
    "You would make a perfect stormtrooper.",
    "WOW! imagine if your parents weren't siblings.",
    "just do exactly the opposite of everything you think and we might have a chance",
    "If your Mom's vagina was a video game it would be rated E for everyone",
    "You should let your chair play, at least it knows how to support.",
    "i bet the last time u felt a breast was in a kfc bucket",
    "I bet you're that guy that dies in the tutorial.",
    "you camp more than Bear Grylls",
    "Please be careful to ensure your tears don't get into the electronics.",
    "Feminists get more trigger time than you.",
    "It's a joke, not a cock, don't take it so hard.",
    "I didn't know they let Stormtroopers play video games",
    "Is your ass jealous of the amount of shit that just came out of your mouth?",
    "If stupidity was a character class, your stats would be legendary.",
    "You must really like spectating your team",
    "If life is like a box of chocolates, you're a fucking raisin",
    "I have bowel movements that move faster than your thought process",
    "When i die i want you guys to lower my coffin so you can let me down one more time",
    "Try not to trip on your skill level on the way out.",
    "Wait, wait, wait. Let me guess. It was lag, wasn't it?",
    "Tried Uploading this to pornhub...but they don't accept rape",
    "I have neither the time nor the crayons to explain this to you.",
    "Stormtroopers aim better than you.",
    "You are why aliens wont talk to us.",
    "Your idea of a comeback is jerking off into a fan",
    "A fucking flight of stairs has killed more people than you have",
    "You need to go back to growing things on Farmville",
    "You're worth less than a Steam trading card",
    "You're the reason they need to put instructions on shampoo bottles.",
    "I'm surprised you even managed to get out of bed without hurting yourself",
    "It's dangerous to use your entire vocabulary in a single sentence!!!",
    "You can start trying any time you like.",
    "There are loads of tutorials online that will show you how to setup your mouse properly.",
    "***PROTIP*** use your mouse to look around",
    "Im considering playing against you with my eyes closed, cause playing one handed didnt make it any harder.",
    "You might help your future win-rate by uninstalling.",
    "Maybe you should try something more your speed.. like stopping",
    "The keys your looking for are Alt-F4",
    "only thing u carry is an extra chromosome",
    "If the game was about getting killed, I bet you would be still alive.",
    "Too bad you weren't in control of the Titanic. You would have missed the Iceberg.",
    "This guy has the map awareness of fucking Christopher Columbus.",
    "I've had jar lids give me a bigger challenge than you.",
    "You're that one guy that would actually get his dick stuck in a ceiling fan for not following instructions.",
    "Stephen Hawkings probably runs better than your game",
    "You must have been born on a highway, because that's where most accidents happen..",
    "I think you dropped a pair of chromosomes right there",
    "There are vacuum cleaners that suck less than you.",
    "If it wasn't for gravity you couldn't even hit the fucking ground",
    "don't trip on your way into respawn",
    "404: Skill not found",
    "If I wanted to kill myself I would jump from your ego down to your IQ",
    "If only you could hit an enemy as much as your dad hits you.",
    "Help & Options -> How To Play",
    "Some babies were dropped on their heads but you were clearly thrown at a wall",
    "Have you considered other hobbies?",
    "I could eat alphabet soup and still shit out a better argument than you.",
    "I hope you're the last person in a human centipede.",
    "hold on im loading my scripts for giving a shit",
    "How are you this bad at support? Do you work for Comcast?",
    "Is your monitor on",
    "are you watching porn or something i swear to god you're playing with one hand",
    "you almost didn't die that time",
    "Shouldn't you be trying to put a round block in a square hole somewhere?",
    "I'd rather fuck a bear trap than live a minute of your life",
    "If only you could hit an enemy as much as your dad hits you.",
    "I'm okay with this team. I work in the city as a garbage collector. I'm used to carrying trash.",
    "I'm super glad you're enjoying the rich tapestry of art assets and sprites, but some of us are trying to win the fucking game",
    "Can someone set the bot difficulty at least to medium, please?",
    "Does your ass ever get jealous of the amount of shit that comes out of your mouth?",
    "You're the reason your parents fight",
    "If the human body is only 65% water then how are you 100% salty?",
    "I recommend you keep crying. It's the only thing you're doing right.",
    "I was pro-life until I met you.",
    "I'm glad to see you took a break from Cookie Clicker to grace us with your MANY talents",
    "Hey, give me a shoutout to your 2 Twitch viewers",
    "No this isn't Pay-To-Win, all you have to do is pay attention",
    "I'm not trash talking, I'm talking to trash",
    "While it is free to play, DOTA 2 is also free to uninstall",
    "Keep rolling your eyes, maybe you'll find a brain back there",
    "You must really like spectating your team",
    "Can you just place your cat on the keyboard and leave? We've a better chance of winning that way.",
    "I bet your club penguin pets killed themselves",
    "Are you constipated? 'cause you ain't doin' shit.",
    "I guess the abortion clinic forgot one",
    "You must be so confused about the tiny people in your computer screen.",
    "why turn on the computer if you're just gonna make it depressed",
    "Remember that one time when you were good at this game? Me neither.",
    "If you keep crying, we're going to need to build another Ark.",
    "This isn't golf dude.  You don't get a handicap.",
    "Be honest, are you just a cat swatting at the keyboard?",
    "This is why people talk about you when you're not around.",
    "Guys, can we put the bots on a higher difficulty?",
    "**PROTIP** Using a mouse is recommended.",
    "Maybe if you stopped using your keyboard as a doormat you could actually win.",
    "I'm actually a dump truck driver because i carry trash like you all day",
    "A law prohibiting you from breeding would be justified but unnecessary",
    "When your parents said shoot for the stars, this is not what they meant.",
    "How many tries did it take for you to click the install button?",
    "Do you need help? I ask cause the only way I can imagine you playing this bad, was if you had collapsed on your keyboard.",
    "I'd call you a piece of shit but that at least has use as fertilizer",
    "Your years of practice on easy bots clearly paid off.",
    "You should eat some makeup so you can at least be pretty on the inside.",
    "Your asshole must be jealous of all the shit that comes out of your mouth.",
    "You couldn't pour water out of a boot if the instructions were on the sole.",
    "You know that if you plug the screen in you can actually see the enemies.",
    "You couldn't be more inbred if you were in a fucking sandwich.",
    "Achievement Unlocked:  More Time Dead Than Alive",
    "To which foundation do I need to donate to help you?",
    "i'm just impressed you're still trying to play with a trackball",
    "You failed, just like your dad's condom",
    "you could season a meal with all that salt from your tears",
    "aww, you're just like Jesus, always respawning and never hurting anyone :)",
    "With all these flavors why do you choose to be salty?",
    "Can you please check if your mouse is plugged in?",
    "Does your mouse have kickback when you shoot?",
    "Can't hear you from the bottom of the scoreboard",
    "All of these flavors and you choose to be salty",
    "I'd suggest you to uninstall the game but I bet it's too complex for you",
    "You're dying so much that you could replace Sean Bean.",
    "What's the difference between you and a bench? The bench can actually support an entire team.",
    "I can't wait till I have dementia so I can forget that ever happened.",
    "I see somebody went to the Stormtrooper school of marksmanship.",
    "I'm pretty sure the only thing you can turn on is your laptop.",
    "I cant hear you at the bottom of the scoreboard",
    "Children with cancer take losing better than you do.",
    "Go play Lemmings, at least you'll be able to kill something.",
    "Does your ass ever get jealous of the amount of shit that comes out of your mouth",
    "I could eat a bowl of alphabet soup and shit out a smarter statement than that.",
    "You deserve a high five, to the face, with a chair",
    "I think you'd have more fun playing something you were good at.",
    "Oops, I must have chosen easy bots by accident",
    "A woman at a urinal has better spray control than you",
    "You can start trying now.",
    "Not even Atlas can carry this Team",
    "Do you lose when you play against yourself?",
    "Have you tried turning your brain off and on again?",
    "There's a good game for you to practice. It's called Cookie Clicker.",
    "If you want to hear about mistakes, ask your parents.",
    "It's a joke, not a cock, don't take it so hard",
    "Is your huge death count compensating for something?",
    "I understand blaming the lag... between your brain and reflexes.",
    "The only thing you are carrying is an extra chromosome",
    "Yes, we know, you have a penis. Please remove it from the keyboard and play.",
    "I'd tell you to blow me but you've been sucking dick all game",
    "Oh wait, this is not a bot game?",
    "I bet if you would go afk, you would play better",
    "Im sure that extra chromosome helps you out with something but it sure as fuck isnt this",
    "I've seen you die more times than I've seen my dad in my whole life.",
    "Hey you got something added to your score. Wait... that's just another death.",
    "Go down to the nearest drugstore and buy a little thing called viagra. It will help you go fuck yourself.",
    "Don't shoot yourself! Not because I'd miss you, because you'd miss you",
    "Even a stormtrooper has a better aim than you",
    "You might just create another dead sea with all your tears.",
    "I wish my HIV-Test would be as negative as your score",
    "you couldn't be more inbred even if you were in a fucking sandwich",
    "You should commit suicide. That way you'd have at least one kill.",
    "Feed any more and you'll end world hunger.",
    "You should make a team and call it 'soup kitchen' cause you're feeding everyone",
    "The only problem with your PC is that thing between your keyboard and your chair",
    "It's just a joke not a dick, don't take it so hard.",
    "Remember that it's better to try and fail than to not try at all, so don't be afraid to start trying any time now",
    "Let's just let natural selection take it's course",
    "I'm trying to see this from your perspective, but I can't seem to get my head that far up my own ass.",
    "Isn't your time running out on the library computer?",
    "You are like Forrest Gump but without the running thing.",
    "I bet you can't see the screen with all your tears",
    "How'd you get through the tutorial?",
    "The way you're feeding, you could feed Africa for a year.",
    "The guy who played CSGO with a wheel is better than you",
    "It was just a joke not a dick, don't take it so hard.",
    "You're about as useful as Anne Frank's drum kit.",
    "A million years of evolution and we get you.",
    "95% of lag occurs between the player and the computer",
    "Correct! I am a tool, because unlike you, I'm actually useful.",
    "Your aim is so poor Bono is holding a charity concert for it.",
    "Well I would agree with you but then we'd both be wrong",
    "If I had 2 bullets and I was in a room with Bieber, Hitler, and you, I'd shoot myself twice.",
    "I don't lift, but I sure do carry.",
    "I'd tell you to kill yourself, but I'm pretty sure you'd miss.",
    "You probably get your insults on CS:GO from a shittalk generator",
    "If I wanted to listen to an asshole, I'd fart",
    "We will get Half-Life 3 when u get a kill.",
    "Maybe Hello Kitty Island Adventure is more around your skill level",
    "at least you could become a stormtrooper",
    "I think you should press the power button in order to contribute to the game.",
    "ethiopia could eat a year the way you are feeding",
    "Atleast you got through the tutorial",
    "Your family tree is a cactus, because everybody on it is a prick.",
    "Your face looks like it was made by Bethesda",
    "Ethiopia could eat for a month the way you are feeding.",
    "Would you like some fries with that salt?",
    "You're the reason your dad drinks",
    "even the steam support is more useful than you",
    "You're supposed to be farming gold, not chromosomes.",
    "I'd tell you to kill yourself, but chances are you'd fuck that up too",
    "Your reaction time is as fast as coastal erosion.",
    "Your existance is proof people don't know how to pull out.",
    "The Escape button is your best and only friend.",
    "The game wants to uninstall you.",
    "You are as useless as a white crayon",
    "The only thing you've killed this game is my faith in you.",
    "Imagine what your life would be if your parents weren't siblings.",
    "I would ask if you were new, but that would imply you can actually get better",
    "Are you playing on pacifist mode?",
    "I guess my team is sponsored by the Make-A-Wish foundation...",
    "If you want to reduce the number of times you lose, you could try uninstalling",
    "How many tries did it take for you to click on the button that launches the game?",
    "At least buy your jungler some marshmallows if he's going to be camping so much",
    "If this was pay-to-win, you'd go bankrupt before you got your first kill.",
    "Auto-sniper just means it's semi-automatic. You stil have to aim.",
    "Access the cheat menu with ALT + F4",
    "Letting you live was medical malpractice",
    "That crosshair is for aiming at enemies, you know.",
    "Two wrongs don't make a right, take your parents as an example.",
    "Don't worry guys, I am a trash man IRL. I am used to carry garbage like you",
    "Does your owner know you're running on the keyboard?",
    "Are you collecting bullets?",
    "Believe in yourself, because the rest of us think you're an idiot.",
    "Mentally challenged people don't want to be referred as 'Retarded' becuase they don't want to be compared with you.",
    "Who set the bots to passive?",
    "PROTIP: Knowing when to quit is a useful skill.",
    "I'm a plumber and even I can't handle your shit.",
    "All the flavors in the world....and you choose to be fucking salty",
    "I would mentally duel with you, but I can see you're unarmed",
    "My cat sleeping on the keyboard would do a better job",
    "Your aim is so poor that people held a fundraiser for it",
    "I'm surprised you even hit the power button on your computer.",
    "Do you want some fries with that salt",
    "Just because you can act like a dumbass doesn't mean you should.",
    "If we learn from our mistakes, your parents must be geniuses now",
    "Friendly fire was invented because of you.",
    "I've seen better reflexes from Bethesda NPCs",
    "Fighting on the internet is like participating in the paralympics. Even if you win, you're still retarded.",
    "Everyone who has ever loved you was wrong",
    "I'm surprised that you were able hit the 'Install' button",
    "Remember, riding dick is not a mode of transportation.",
    "I don't have the time or the crayons to explain this to you.",
    "I noticed your sister got all the good genes from the family.",
    "Maybe it's time to upgrade from dial up.",
    "Next round, you should try looking at the monitor.",
    "My abacus has more processing power than you.",
    "I was going to make a joke about your kills but I couldn't find any.",
    "At least your immune system tries to stop you from dying.",
    "People like you demonstrate why Single Player mode should be mandatory.",
    "Whoever told you to just be yourself couldn't have given you worse advice",
    "That respawn timer might be one of your best friends right?",
    "Your aim is so shit you couldn't hit the ground if you fell",
    "Are you worried about the moral consequences of killing someone in a game?",
    "You are the reason I have to doubt evolution and natural selection",
    "Unplug the Ethernet cable. That gets rid of the lag.",
    "Your existence is the reason for scientists to rethink the plausibility of evolution.",
    "I didn't realize 'Moving Target Dummy' was a selectable character.",
    "They say you are what you eat. Do you eat shit for breakfast?",
    "Try switching your router off, that might help.",
    "'Three-second burst' should be your rate-of-fire, not your life expectancy",
    "The way you're feeding, you could end world hunger.",
    "Your aim is proof that excessive masturbation causes blindness",
    "Maybe if you try to miss, you might hit something!",
    "Even the game's client-side prediction has no idea what you're trying to do.",
    "I would call you AIDS but at least AIDS gets kills",
    "You probably think the light in the refrigerator never turns off.",
    "I don't have the time or the crayons to explain this to you.",
    "I've had more engaging arguments with my dog",
    "I almost mistook you for an actual threat there.",
    "You could end world hunger with how much you feed",
    "You must have been born on a highway, because that's where most accidents happen.",
    "Not even Noah carried this many animals",
    "'Twitch Plays TF2' would be more useful than you.",
    "I've been to daycares more threatening than you",
    "press alt-f4 to help the team",
    "Don't worry, everybody was new once. You just... stayed.. new, somehow...",
    "John Lennon is better at dodging bullets than you",
    "The only keys that's worth hitting, is that power button on your computer.",
    "I believed in the good and potential of humanity. And then you came along.",
    "If you stopped jerking off, maybe the blood would go to your brain instead.",
    "It's sad that your IQ matches your shoe size.",
    "Two wrongs don't make a right, take your parents for instance",
    "You know what man, blind gamers deserve a chance too. I support you.",
    "You could play in an empty server and still somehow manage to lose CTF.",
    "If I wanted to get yelled at by folks like you, I would go to the daycare.",
    "I normally don't argue with children but I'll make an exception for you.",
    "I didn't know dying was a special ability.",
    "You'd have made an excellent Stormtrooper",
    "You're just like a dog, all bark and unable to play video games.",
    "Play with a blindfold on, at least you'll have a valid reason for missing all those shots.",
    "Only thing you carry is an extra chromosome.",
    "Like the Dead Sea wasn't salty enough.",
    "At least your K/D is better than your GPA.",
    "Why don't you check between your chair and your keyboard for the problem?",
    "Warmup ended several rounds ago.",
    "You know this isn't turn based combat right? When they shoot at you feel free to shoot back.",
    "Did you empty your ammo for warning shots?",
    "stop hogging all the deaths",
    "Did Marvel buy the rights to your mouse?  Because you can't seem to actually kill anybody off.",
    "Stairs has killed more people than you have.",
    "Blink twice if your skill is being held hostage.",
    "Try doing hand stands sometimes. I think your brain needs more blood.",
    "You're the type of person who would miss at point blank range with a flamethrower.",
    "30 millon sperm and you swam the fastest?",
    "I see you gained a new hobby, Collecting Bullets.",
    "If you ever win a match screencap and send to the church. Pretty sure that'll count as a miracle.",
    "Good job keeping your learning curve perfectly horizontal.",
    "You have some big balls on you. Too bad they belong to the guy fucking you from behind.",
    "Your aim is so bad you couldn't hit water if you fell out of a boat",
    "Congress works better than you.",
    "Your mind is just as stable as your internet connection.",
    "How the fuck were you the fastest sperm???!",
    "Players like you are why Easy mode is a difficulty option.",
    "You know your team is trying to win right?",
    "If you were a real terrorist, the world would be a much safer place.",
    "Perhaps you should try something more innovative, like playing.",
    "You make stormtroopers look good.",
    "I think you should just go afk. You'd get better results.",
    "I'd agree with you, but then we'd both be wrong.",
    "Even Gandhi is jealous of your pacifist playstyle.",
    "I think you should stick to Neopets.",
    "You're the reason abortion was legalized",
    "Team Fortress 2 is also free to unistall",
    "Arguing on the internet is like competing in the special Olympics. Even if you win, you are still retarded.",
    "Even a common cold has a higher kill count than your aim",
    "God ran out of clay, so he slapped a bunch of dog shit together to make you",
    "Were you always this shitty or you're trying really hard today?",
    "Does your mouse have recoil or something?",
    "I never knew you could play this from your IPad",
    "You aim like Michael J. Fox on a roller coaster",
    "Not even Noah could carry these animals.",
    "You're about as useful as a snowshovel in Hawaii.",
    "Out of any animal you identify with, you chose a bitch.",
    "Good job, now try that on the other team!",
    "Don't beat yourself up. We already did that for you.",
    "Stephen Hawking has better hand-eye coordination than you.",
    "You must have been born on a highway, because that's where most accidents happen",
    "I bet you have alot of participation awards...",
    "Move your sisters head, I'm gonna kick you in the dick",
    "I'm Sorry I Can't Hear you From the Bottom of the Scoreboard",
    "Your best Kill of the Day: my time",
    "I'd tell you where the uninstall button is but you'd miss that one too",
    "You're lucky your dad's dick had better aim than you.",
    "You didn't make a mistake. Your parents did.",
    "Why don't you slip into something more comefortable? Like a coma?",
    "If Stupid was an epidemic, you must be patient zero.",
    "I see your hobbies include lag, friendly fire and caps lock. Good for you.",
    "It'd be an insult to compare a stormtrooper to you. At least they know what they're trying to shoot at.",
    "How did you ever get through the tutorial level?",
    "I wonder if you last as long in bed as you do in this game.  I'd ask your girlfriend, but hands can't talk.",
    "You are the MVP of the other team.",
    "Your mother should have swallowed you",
    "You'd have the top score if this was golf",
    "Rick Astley gave you up 'cause you let him down.",
    "Maybe you should just stick to playing singleplayer games.",
    "your birth certificate came with an apology letter from condom factory.",
    "Stormtroopers hit their targets more than you.",
    "I don't know what your problem is, but I bet its hard to pronounce",
    "I wonder if the sperm that had the skills is watching you from your mom's mattress.",
    "The way you feed, you could stop world hunger.",
    "Just because you have the ability to click play doesn't mean you should.",
    "It seems you and the kill cam have become well acquainted",
    "Most people missed out on the lottery, you missed out on the gene pool.",
    "You're the MVP of the other team",
    "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
    "You could win an oscar for how sad your life is.",
    "Embarrassing. I've heard better shittalking from a goddamn crowdsourced generator",
    "I've seen more support for North Korea than I've seen all game from you.",
    "Just as a heads up Steam has a 2 hour, no questions asked refund policy. I suggest you take advantage of it while you can.",
    "Do you ever wonder what life would be like if you'd had enough oxygen at birth?",
    "You are the reason aliens wont talk to us",
    "Your family tree is a cactus because everybody on it is a prick.",
    "You are proof enough that guns do not kill people.",
    "Stevie Wonder can see how shit you are",
    "I think I broke the weightlifting record by carrying this team.",
    "It is dangerous to use your whole vocabulary in one sentence.",
    "Congratulations! You've made the enemy team's highlight reel!",
    "If skills were a disease, you'll be immune to it.",
    "Only thing you're carrying is an extra chromosome.",
    "You remind me of the last batch of scrambled eggs I made: beaten, over-salted, and burned.",
    "Maybe God made you a bit too special.",
    "Your kill list is shorter than a list of french war heroes",
    "If we were playing a game in which the objective were to shoot walls, you would still lose.",
    "I'm still not convinced God exists, but if he does you prove he has a sense of humor.",
    "I would ask you how old you are but I know you can't count that high.",
    "Calling you a retard is an insult to the mentally challenged",
    "I bet you would blame it on the lag at a LAN party too.",
    "Why are you still here? I thought trash day was yesterday.",
    "It's quick, it's easy, and it's free: Trying.",
    "I would insult your IQ, but the concept of negative numbers would boggle your mind.",
    "Don't you love nature, despite what it did to you?",
    "If your dad's aim was as good as yours we wouldn't be talking right now.",
    "I'd tell you to go play in traffic, but you'd probably suck at that too.",
    "I'd call you cancer, but at least cancer kills.",
    "I'm sure your bodypillow is very proud of you.",
    "I bet he came here because Minecraft was too hard",
    "Did your parents try to get a refund?",
    "Now I know why nearly every game has arrows pointing to the objective. They were all for you.",
    "Playing with you is like the Shawshank Redemption, only with more tunneling through shit and no fucking redemption.",
    "The only thing you carry is an extra chromosome",
    "I`d call you cancer, but cancer actually gets kills",
    "When I die I want you guys to lower my coffin so you can let me down one last time.",
    "The killcam ran out of film thanks to you.",
    "I'd call your aim cancer, but at least cancer can kill people.",
    "Do your parents cry every day or just on the days they realize they didn't get the abortion?",
    "Pro Tip: You can uninstall any game you play.",
    "If your face was a Counter Strike map, it would be de_formed.",
    "I bet you blame the lag even when you're playing with bots.",
    "Your aim is so poor, even African countries feel the need to donate to you.",
    "Imagine going through 9 months of pregnancy to give birth to a child who doesn't push the payload.",
    "Are you AFK? Good, we finally have a chance of winning.",
    "You couldn't hit water if you fell out of a boat.",
    "This is why doctors advocate regular masturbation, to keep fuck ups like you from being conceived.",
    "Your parents aren't the only ones who regret knowing you",
    "You're a prime example of why the gene pool needs a whole lot of bleach",
    "Did you skip the tutorial?",
    "You're like an onion. On the outside you're shit, but peel away a layer and underneath is another layer of shit",
    "Even Atlas couldn't carry you",
    "You are a living contradiction to evolution.",
    "I have neither the time, nor the crayons, to explain this to you..",
    "My shoes have more support than you've given me.",
    "You paid $1500 just to get destroyed in 4k. Good Investment.",
    "Your aim is like your crush, never gonna hit it",
    "please look at the screen when you are playing",
    "I'd say you suck, but that would mean you have some value",
    "I feel like you are the type of person to go negative against bots",
    "When i die i want you guys to lower my coffin so for once you can carry me.",
    "If ignorance is bliss you must be the happiest person alive.",
    "please look at the screen when you are playing",
    "You  have an inferiority complex, and it's completely justified",
    "I'm sorry, you'll have to be louder- sound doesn't travel all the way up the scoreboard.",
    "it was a joke, not a dick, don't take it so hard..",
    "I guess the condom broke and the coat hanger wasn't long enough.",
    "If I wanted to kill myself I'd jump from your ego down to your rank",
    "You're the reason negatives numbers exist",
    "With that aim, I'm impressed you could even hit the queue button.",
    "I would tell you to shoot yourself, but you'd miss.",
    "Hitler knew when to kill-himself. Why can't you do the same?",
    "Could you please play with both hands?",
    "Imagine that someone was pregnant for nine months, gave birth, and their child doesn't even play the fucking objective.",
    "Were you born on a freeway? Because that's where most accidents happen.",
    "If you were any dumber I would have to water you twice a day",
    "Do you know you need a mouse to play, right?",
    "You can turn on your monitor now.",
    "When you go to a family reunion, who brings the condoms?",
    "You're baiting so hard you could probably catch a fucking shark",
    "There are about 37 trillion cells working together in your body right now, and you are disappointing every single one of them.",
    "video games bring new experiences and right now I'm experiencing what it's like to be a special needs caretaker",
    "Do you lose when you play against yourself too?",
    "I must be Noah's Ark. I'm carrying a bunch of fucking animals",
    "I'd give a penny for your thoughts, but I don't want to overspend.",
    "Of all these different flavours, you chose to be salty.",
    "If I got a dollar every time you missed a shot i could buy you the glasses you so desperately need.",
    "You could be the only person in the game and still manage to die.",
    "You don't have to worry about friends talking shit behind your back, seeing you have none.",
    "The only thing you carry is aids",
    "you're topping the scoreboard in chromosome count",
    "You might as well start hacking, that way you could finally achieve something; a ban.",
    "Your K/D would vastly improve if you killed yourself",
    "You're as useful as a white crayon",
    "You should give that extra chromosome back, it's not nice to steal",
    "I wish we'd met years ago, I would have repressed the memory by now",
    "At least terminal cancer gets kills.",
    "So many flavors to choose from, and yet you choose salt",
    "Can a medic take a look at my back? It hurts from carrying this team.",
    "I doubt you can even count to your score.",
    "imagine going through 9 months of pregnancy to give birth to a child who doesn't push the fucking payload.",
    "Do you believe in God ? cause he doesn't believe in you.",
    "You probably would've shot the kid instead of Harambe",
    "Have you considered pointing that gun the other way around?",
    "I can't carry you with all those extra chromosomes weighing you down.",
    "I'd call you cancer, but at least cancer gets kills.",
    "does your ass ever get jealous of all the shit that comes out of your mouth?",
    "You are the reason why abortion is legal.",
    "Imagine going through 9 months of pregnancy just to give birth to a child who doesn't push the fucking payload",
    "You have as many kills as you have brain cells.",
    "I'd agree with you, but then we'd both be wrong",
    "PROTIP: you have a second hand for the keyboard",
    "Guys, how about you fix some handles to yourselves, so it'll be easier for me to carry you?",
    "I need an apology letter. Can I borrow your birth certificate?",
    "im gonna be able to deadlift 400 pounds by the time im done carrying you",
    "This team could lose at Farmville.",
    "Ah yes, the Dead Sea, the second saltiest thing on Earth next to your bitch ass.",
    "You should've quit while you were ahead. Which was before you installed.",
    "You sound like you roofy yourself at gay bars",
    "Kirby must be jealous with how much you suck.",
    "With a score as low as that, you must be amazing at golf.",
    "I've avoided smoking my entire life to prevent cancer, but with a play like that it seems I've missed out on cigars for nothing.",
    "Mistakes were made, the worst one was by your parents.",
    "I'd call your aim cancer, but cancer kills",
    "At least you could survive the abortion.",
    "You're living testament to the idea that people only use 10% of their brains",
    "If you'd been the terrorist piloting the jet in 9/11, the towers would probably still be there",
    "Did you know sharks only kill 5 people each year? Looks like you got some competition",
    "I've never touched a cigarette. I feel a sense of regret for not doing it, because you gave me cancer anyway.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "if you open up enough crates, one might contain the chromosome you left inside your mom.",
    "I was anti-abortion before I started this match but now I'm reconsidering.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "I'd call all of you cancer, but at LEAST cancer kills.",
    "Why is there an enemy team when I have my own shit teammates to deal with.",
    "You are a walking condom advertisment.",
    "Your parents deserve more than this.",
    "I'd say your aim is cancer, but cancer actually kills",
    "You're more fucked than a Ditto in day-care.",
    "Christopher Columbus has better map awareness than you",
    "If you worked at a zoo, Harambe would still be alive.",
    "When I die, I'd like you to lower my coffin, so you can let me down one last time.",
    "I'd tell you to just end it and shoot yourself, but you'd probably miss.",
    "I would call you a cunt, but a cunt has a use.",
    "I bet you guys are going to single-handedly keep the porn industry alive for the next 30 years.",
    "I'd call you cancer, but it kills.",
    "I wish I could replace Harambe with you",
    "You guys answered the age-old question of whether God could create a team of people so dense that even he could not carry them",
    "You're why I'm pro-choice.",
    "Stupid people can believe in anything, so you can believe in yourself",
    "Somehow you are doing worse than Ghostbusters.",
    "Please tell me you're actually a 'Twitch Plays' script",
    "It's not that I hate you, you just don't deserve respect in the first place.",
    "Comcast gives better support than you.",
    "I'd say you're cancer but at least cancer can kill people",
    "You couldn't even hit puberty.",
    "Your birth certificate was an apology from the condom company.",
    "Michael J. Fox would be a better sniper main than you",
    "I bet you guys are going to single-handedly keep the porn industry alive for the next 30 years the way you're fucking us.",
    "I'd ask you to shoot yourself, but you'd probably still miss.",
    "Your parents must have been disappointed with the one-child policy",
    "I know you're trying your best, but I wish your best was actually trying.",
    "If I wanted an excuse, I would've asked your mother why you weren't aborted.",
    "Your Tinder profile has seen more lefts than a Nascar track",
    "Roman soldiers were once paid in salt. These days people like you are giving it out for free.",
    "I wish you took the bullet instead of Harambe.",
    "I'd try to see things from your point of view but I couldn't get my head that far up my ass.",
    "Team Fortress2 is also Free-To-Uninstall",
    "Your parents need to get a very late term abortion",
    "I'd trade you for a park bench, at least it could support the team",
    "I used to think everyone had the potential to be great, then I discovered you.",
    "I would have been you for Halloween, but I couldn't fit 7 dicks in my mouth",
    "I'd call my team cancer, but at least cancer kills.",
    "I would unplug your life support to charge my phone.",
    "You look like someone pressed the randomize button in the Oblivion character creator.",
    "You couldn't pour water out of a boot with instructions on the heel",
    "Fuck yourself. You'll finally get some pussy that way.",
    "You bring down the property value just being here.",
    "You say that as if I value your opinion.",
    "If you listen closely, you can actually hear the salt crystals forming",
    "You're living proof that God has a sense of humour",
    "This game has a wide variety of playable characters and playstyles, and I'd appreciate it if you'd learn one.",
    "You couldn't even support a drug addiction",
    "You're the type of player to get 3rd place in a 1v1 match",
    "I used to be an athiest but only divine intervention could create something as miserable as you.",
    "If I were to insult you, it'd be animal abuse",
    "Each time you spend time typing, we actually do better.",
    "I'd call you cancer, but cancer gets kills.",
    "The only thing that will ever fuck you, is life.",
    "If you got cancer, I would feel bad for the cancer.",
    "You'd struggle to pour water out of a boot if the instructions were written on the heel!",
    "You couldn't pour water out of a boot if the instructions were on the heel",
    "The only thing you can throw is the match",
    "I'd call you a tool, but that would imply you were useful in at least one way.",
    "I'm reconsidering creationism, I feel like it only took 6000 years of evolution to make you.",
    "Your existence is the best argument against intelligent design.",
    "When I die I want you to to lower me in my grave so you can let me down one more time.",
    "Two men walk into a bar. You walk into a fucking pole.",
    "Really wish I could aim this gun at myself instead of the enemy team.",
    "Wait, don't go. I still need more salt on my food.",
    "Imagine going through 9 months of pregnancy only to give birth to someone who decides to be the fucking fourth spy on the team.",
    "If we win this game, you only need one more miracle to become a saint.",
    "I'd call you cancer, but at least cancer kills people.",
    "You're the type of person to try and shoot up a school with a nerf gun",
    "Legend has it that the number 0 was first invented after scientists calculated your chance of doing something useful.",
    "You are probably the only person that will miss with an aimbot.",
    "I'd call you a cunt, but you lack the warmth or the depth.",
    "Which is lower, your score or your IQ?",
    "If I wanted to kill myself, I would climb up to your ego and jump down to your IQ level",
    "You're as useful as Stephen Hawking's home gym",
    "I regret not smoking my entire life, because watching you still gave me cancer.",
    "Remember when your mother told you to be yourself? Please don't do that.",
    "Surprised you got past the tutorial honestly",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "If there would be a loser contest you'd win a second place. Because you are a loser.",
    "You're an inspiration for birth control.",
    "We should call this team 'The Stormtroopers' cause none of you can fucking hit anything.",
    "With that poor aim, im surprised your dad figured out where to stick it in",
    "Harambe didn't die for this.",
    "ergkirhrjrl;asewi    shit, sorry, my cat walked on my keyboard and somehow it still played better than you.",
    "Save your breath, you'll need to to blow up your girlfriend later.",
    "I would say this team is cancer, but at least cancer gets kills",
    "I'd call you cancer but at least cancer can kill things",
    "I'd rather have a single Stormtrooper than any of these fucking Snipers.",
    "If I had a dollar for every time you missed a shot I could buy you the glasses you so desperately need.",
    "I've seen obese Mexican food vendors push carts better than this team.",
    "your hand to eye coordination is more broken than TF2's matchmaking system",
    "If you were any more inbred you'd be a sandwich",
    "If I wanted to kill myself I'd jump from your ego down to your IQ.",
    "Imagine going through 9 months of pregnancy to give birth to a child who doesn't do the fucking objective.",
    "I'm a support main but I can't heal this team's cancer.",
    "The only game you could get a high score in is golf.",
    "Team Fortress 2 is also Free-To-Uninstall,",
    "Stephen Hawking knows the secrets of the universe; but can't figure out how people as stupid as you put on shoes this morning.",
    "Iridium is known to be the second densest thing on the planet. Congrats on being more dense than Iridium.",
    "Aiming can increase your accuracy.",
    "Harmless bots have a higher K/D than you",
    "Imagine going through a nine month pregnancy only to give birth to someone who can't push the fucking cart.",
    "If I wanted to stay suspended in motion I would jump from your ego down to your IQ.",
    "You need a higher aspiration in life than just being a giant fucking failure, buddy.",
    "When I die, I want you to put my casket into my grave, so that you can let me down one last time.",
    "When scientists finally find what the object at the centre of our galaxy, it's going to be your dense fucking head",
    "I had no expectations for you and yet you still managed to disappoint. Bravo.",
    "I would tell you a joke, but your entire existence makes a better job at that than me.",
    "You can mine salt from the ground, or you can dry seawater. I don't have to do either, I've got you.",
    "Next time, use leftclick to shoot.",
    "Suicide is always an option.",
    "You remind me of the son I never wanted",
    "How about you stop carrying the other team?",
    "Tip : Turn on your monitor to see what's ahead of you!",
    "Strange, I thought the counter didn't track kills on bots",
    "Your mom should of swallowed you",
    "31.5 N, 35,5 E, the coordinates of the Dead Sea, the saltiest place on earth next to your bitch ass.",
    "You weren't worth the sex that made you.",
    "A fortune teller told me that I was going to kill a vegetable today, I guess that time is now...",
    "My back hurts from carrying this team",
    "I'd make a joke, but you're already here",
    "You look like your face was on fire and someone tried to put it out with a fork",
    "If I wanted you to open your mouth I'd jingle my zipper",
    "If you were to shoot yourself, your K/D ratio would improve by 100%.",
    "Imagine waiting 9 months to give birth, and it's you.",
    "players like you should come with a handicap sticker",
    "Eat your veggies kids, that's how I got strong enough to carry you all",
    "If you made as many good plays as made excuses, you'd have won EVO by now.",
    "The only excuse you can have for doing THIS bad, is that you're using the DK bongos as a controller.",
    "You lost the game for us? Don't worry, everyone makes mistakes, even God does, we have you to show for it!",
    "Imagine being pregnant for nine months only to give birth to a fucking idiot who thinks recycling this joke is a good idea.",
    "What you lack in brain cells, you make up for in chromosome count.",
    "It must be difficult for you, exhausting your entire vocabulary in one sentence.",
    "You're more useless than Anne Frank's drumkit",
    "You're such a pussy that fucking you wouldn't be gay.",
    "Calling you a retard is a compliment in comparison to how stupid you actually are.",
    "I would insult you, but my parents always told me not to abuse the profoundly handicapped.",
    "I'm not saying you're useless, but I'd unplug your router to charge my phone.",
    "Wow, this game should really be R-rated. I'm looking at the killfeed and all it shows is our team getting fucked.",
    "You're the reason why no religion has a god that stays on Earth.",
    "They should put you on pamphlets as a warning to teenagers.",
    "I'd insult your mother, but I'd hurt your sister's feelings.",
    "The way you're feeding, Africa may finally have a chance.",
    "At least your ping is higher than your death count.",
    "You're the reason they need to put instructions on Bleach bottles",
    "If laughter is the best medicine, your face must be curing the world.",
    "Your mother should've spent the money on an abortion rather than the booze she drank during the pregnancy.",
    "Your waifu is like the way you play: shit.",
    "You whine more than a hentai girl does. At least she's actually useful.",
    "Christ died for your sins and this is how you repay him?",
    "Why don't you slip into something more comfortable...like a coma.",
    "If you're going to be two-faced, at least make one of them pretty.",
    "Shhh, you're 12, you still need permission to use club penguin.",
    "Dropped Like A Newborn Baby",
    "Unplug your mouse and throw it at your monitor, you'll probably hit more of your shots.",
    "I'd say your aim is cancer, but cancer actually kills people.",
    "What's the similarity between your mom and you? Both you and your mom suck.",
    "Could you imagine what it would have been like if you had more oxygen at birth",
    "Its a shame you werent the pilot of 9/11, you would have missed the building.",
    "just because it's on the scoreboard, it doesn't mean dying gets you points",
    "Just fucking throw your mouse at your screen, that'll be the first shot you hit. You know what? You'll just miss that too.",
    "1v1 me in club penguin m8 ill beat ur sorry azz",
    "I sometimes contemplate suicide, but then who would be around to tell you how terrible you are.",
    "I've seen better reflexes from Polio sufferers.",
    "The only thing that you can hit is rock-bottom.",
    "Calm down kid, this isn't a Snickers commercial",
    "Weird, I didn't know they let bots run loose in public games?",
  ];


	robot.respond(/!?shittalk/i, function (res) {
    var i = Math.floor(Math.random() * responses.length);
		res.send(responses[i]);
  });
};
